[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

# [etherscan]
# sepolia = { key = "${ETHERSCAN_API_KEY}" }

[profile.sepolia]
fork = "https://sepolia.infura.io/v3/${INFURA_PROJECT_ID}"
chain = "sepolia"